[workspace]
resolver = "2"
members = ["contract", "tools/prover"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "fat"
strip = "symbols"
panic = "abort"
overflow-checks = false
debug = false

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
near-sdk = "5.5"
near-workspaces = "0.15"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
borsh = "1"
