//! End-to-end connected-flow integration test driven by snarkjs fixtures.
//!
//! Deploys the REAL `groth16-verifier` build of the shielded-pool contract to a
//! near-workspaces sandbox, initialises it with snarkjs VKs from the committed
//! `circom/fixtures/{deposit,transfer,withdraw}/vk.bin` files, then replays a
//! CONNECTED deposit-A → deposit-B → transfer → withdraw flow by reading the
//! pre-generated proof bytes from `circom/fixtures/e2e/{deposit_a,deposit_b,
//! transfer,withdraw}/{proof.bin,params.json}`.
//!
//! Connected scenario (generated by `circom/scripts/gen-e2e-fixtures.ts`):
//!   sk = 7, auditorPubkey32 = 0x42..0x61 bytes
//!   1. Deposit A: amount=60 → commitmentA at tree index 0
//!   2. Deposit B: amount=40 → commitmentB at tree index 1 → root R2
//!   3. Transfer:  spend A(60)@0 + B(40)@1 at R2 → out0(70)@2, out1(30)@3 → root R3
//!   4. Withdraw:  spend out1(30)@3 at R3 → bob.test.near, relayerFee=2
//!
//! Drift guard: asserts that the r1cs SHA-256 hashes in `circom/fixtures/meta.json`
//! match the current build artifacts (if the build directory is present).  Absent
//! build artifacts → fixture-only assertion (proof.bin len + vk.bin len).
//!
//! The per-step root-parity assertions (`root_after_*` in params.json vs. the live
//! sandbox merkle_root view) are the enforcement of the invariant that the
//! fixture-generator's off-chain tree insertion order must exactly mirror the
//! contract's IncrementalMerkleTree insertion order; if that invariant breaks the
//! assertions here will catch it before a proof is submitted with the wrong root.
//!
//! Gated by `SKIP_NEAR_INTEGRATION` env var (proof bytes still validated).

use near_sdk::json_types::U128;
use serde_json::json;
use std::collections::HashMap;

/// REAL groth16-verifier WASM (NOT the `.integration.opt.wasm` mock build).
const OPT_WASM_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../target/wasm32-unknown-unknown/release/shielded_pool.opt.wasm"
);
const RAW_WASM_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../target/wasm32-unknown-unknown/release/shielded_pool.wasm"
);

// VK binary files: written by gen-fixtures.ts, circuit-level (not scenario-specific).
const VK_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../circom/fixtures");

// E2E fixture directories.
const E2E_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../circom/fixtures/e2e");

// Circom build dir (for drift guard).
const BUILD_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../circom/build");

// ---------------------------------------------------------------------------
// Drift guard
// ---------------------------------------------------------------------------

/// Assert that the committed r1cs SHA-256 hashes in `circom/fixtures/meta.json`
/// still match the current build artifacts. If the build directory is absent,
/// fall back to shape assertions on the committed fixture binaries only.
fn assert_fixture_not_drifted() {
    let meta_path = format!("{VK_DIR}/meta.json");
    let meta_raw = std::fs::read_to_string(&meta_path)
        .unwrap_or_else(|_| panic!("cannot read {meta_path}"));
    let meta: HashMap<String, serde_json::Value> =
        serde_json::from_str(&meta_raw).expect("meta.json must be valid JSON");

    let circuits = ["deposit", "transfer", "withdraw"];

    for c in &circuits {
        let entry = meta.get(*c).unwrap_or_else(|| panic!("meta.json missing circuit '{c}'"));

        // --- vk.bin shape check (always) ---
        let vk_path = format!("{VK_DIR}/{c}/vk.bin");
        let vk_bytes = std::fs::read(&vk_path)
            .unwrap_or_else(|_| panic!("cannot read {vk_path}"));
        // VK = alpha_g1(64) + beta_g2(128) + gamma_g2(128) + delta_g2(128) + IC[0..n](64 each)
        // nPublic determines IC length: IC.len() = nPublic + 1.
        let n_public = entry["nPublic"].as_u64().unwrap_or_else(|| panic!("meta.json[{c}].nPublic missing")) as usize;
        let expected_vk_len = 64 + 128 + 128 + 128 + (n_public + 1) * 64;
        assert_eq!(
            vk_bytes.len(),
            expected_vk_len,
            "vk.bin for '{c}' has wrong length: got {}, expected {expected_vk_len}",
            vk_bytes.len()
        );

        // --- proof.bin shape check (always) ---
        for step in ["deposit_a", "deposit_b", "transfer", "withdraw"] {
            let circuit_for_step = match step {
                "deposit_a" | "deposit_b" => "deposit",
                other => other,
            };
            if circuit_for_step != *c {
                continue;
            }
            let proof_path = format!("{E2E_DIR}/{step}/proof.bin");
            let proof_bytes = std::fs::read(&proof_path)
                .unwrap_or_else(|_| panic!("cannot read {proof_path}"));
            assert_eq!(
                proof_bytes.len(),
                256,
                "e2e/{step}/proof.bin must be 256 bytes, got {}",
                proof_bytes.len()
            );
        }

        // --- r1cs sha256 check (only if build dir is present) ---
        let r1cs_path = format!("{BUILD_DIR}/{c}.r1cs");
        if std::path::Path::new(&r1cs_path).exists() {
            let r1cs_bytes = std::fs::read(&r1cs_path)
                .unwrap_or_else(|_| panic!("cannot read {r1cs_path}"));
            let digest = sha256_hex(&r1cs_bytes);
            let expected = entry["r1csSha256"].as_str().unwrap_or_else(|| panic!("meta.json[{c}].r1csSha256 missing"));
            assert_eq!(
                digest,
                expected,
                "DRIFT DETECTED: circom/{c}.r1cs sha256 changed. \
                 Regenerate fixtures with: bash circom/scripts/regen-fixtures.sh"
            );
            eprintln!("drift-guard: {c}.r1cs sha256 matches meta.json ✓");
        } else {
            eprintln!("drift-guard: {c}.r1cs absent, skipping r1cs hash check (fixture shape only)");
        }
    }
}

/// Compute SHA-256 hex of a byte slice using the `sha2` crate.
fn sha256_hex(data: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    hex::encode(Sha256::digest(data))
}

fn skip() -> bool {
    std::env::var("SKIP_NEAR_INTEGRATION").is_ok()
}

/// Loads the deployable groth16-verifier WASM, running wasm-opt if needed.
fn load_deployable_wasm() -> anyhow::Result<Vec<u8>> {
    if !std::path::Path::new(OPT_WASM_PATH).exists() {
        anyhow::ensure!(
            std::path::Path::new(RAW_WASM_PATH).exists(),
            "missing groth16-verifier wasm at {RAW_WASM_PATH}. Build with: \
             cargo build -p shielded-pool --target wasm32-unknown-unknown --release \
             --no-default-features --features groth16-verifier"
        );
        let status = std::process::Command::new("wasm-opt")
            .args([
                "--enable-bulk-memory",
                "--llvm-memory-copy-fill-lowering",
                "-Oz",
                "--strip-debug",
                "--strip-producers",
                RAW_WASM_PATH,
                "-o",
                OPT_WASM_PATH,
            ])
            .status()
            .map_err(|e| {
                anyhow::anyhow!(
                    "wasm-opt not found ({e}); produce the deployable artifact with: \
                     wasm-opt --enable-bulk-memory --llvm-memory-copy-fill-lowering -Oz \
                     --strip-debug --strip-producers {RAW_WASM_PATH} -o {OPT_WASM_PATH}"
                )
            })?;
        anyhow::ensure!(status.success(), "wasm-opt failed");
    }
    Ok(std::fs::read(OPT_WASM_PATH)?)
}

/// Read params.json for an e2e step.
fn read_params(step: &str) -> serde_json::Value {
    let p = format!("{E2E_DIR}/{step}/params.json");
    let raw = std::fs::read_to_string(&p).unwrap_or_else(|_| panic!("cannot read {p}"));
    serde_json::from_str(&raw).unwrap_or_else(|_| panic!("{p} is not valid JSON"))
}

/// Read proof.bin for an e2e step.
fn read_proof(step: &str) -> Vec<u8> {
    let p = format!("{E2E_DIR}/{step}/proof.bin");
    let b = std::fs::read(&p).unwrap_or_else(|_| panic!("cannot read {p}"));
    assert_eq!(b.len(), 256, "e2e/{step}/proof.bin must be 256 bytes");
    b
}

/// Deposit via the production NEP-141 ft_on_transfer path.
async fn ft_deposit(
    usdc: &near_workspaces::Account,
    pool_id: &near_workspaces::AccountId,
    sender_id: &near_workspaces::AccountId,
    commitment: &str,
    amount: u128,
    auditor_pubkey: &str,
    view_ct: &str,
    note_ct: &str,
    proof: &[u8],
) -> anyhow::Result<near_workspaces::result::ExecutionFinalResult> {
    let msg = serde_json::to_string(&json!({
        "commitment": commitment,
        "amount": U128(amount),
        "auditor_pubkey": auditor_pubkey,
        "view_ct": view_ct,
        "note_ct": note_ct,
        "proof": proof,
    }))?;
    Ok(usdc
        .call(pool_id, "ft_on_transfer")
        .args_json(json!({
            "sender_id": sender_id,
            "amount": U128(amount),
            "msg": msg,
        }))
        .max_gas()
        .transact()
        .await?)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[tokio::test]
async fn snarkjs_connected_flow_deposit_transfer_withdraw() -> anyhow::Result<()> {
    // Always: drift guard + fixture shape assertions.
    assert_fixture_not_drifted();

    // Always: assert proof.bin sizes for all e2e steps.
    for step in &["deposit_a", "deposit_b", "transfer", "withdraw"] {
        let _ = read_proof(step); // panics if missing or wrong length
    }

    if skip() {
        eprintln!("SKIP_NEAR_INTEGRATION set; fixture assertions passed, skipping sandbox");
        return Ok(());
    }

    // ----- Deploy groth16-verifier WASM + init with snarkjs VKs -----------
    let pool_wasm = load_deployable_wasm()?;

    // VKs are from circom/fixtures (written by gen-fixtures.ts, scenario-independent).
    let vk_deposit = std::fs::read(format!("{VK_DIR}/deposit/vk.bin"))?;
    let vk_transfer = std::fs::read(format!("{VK_DIR}/transfer/vk.bin"))?;
    let vk_withdraw = std::fs::read(format!("{VK_DIR}/withdraw/vk.bin"))?;

    let worker = near_workspaces::sandbox().await?;
    let pool = worker.dev_deploy(&pool_wasm).await?;
    // Stand-in USDC account: only the predecessor-guard check matters.
    let usdc = worker.dev_create_account().await?;
    let alice = worker.dev_create_account().await?;

    let init = pool
        .call("new")
        .args_json(json!({
            "owner": pool.id(),
            "usdc_token": usdc.id(),
            "vk_deposit": vk_deposit,
            "vk_transfer": vk_transfer,
            "vk_withdraw": vk_withdraw,
        }))
        .max_gas()
        .transact()
        .await?;
    assert!(init.is_success(), "init failed: {init:#?}");

    let pre_root: String = pool.view("merkle_root").await?.json()?;
    eprintln!("pre_root: {pre_root}");

    let one_near = near_sdk::NearToken::from_near(1).as_yoctonear();

    // ----- DEPOSIT A (amount=60, index=0) -----------------------------------
    let params_a = read_params("deposit_a");
    let proof_a = read_proof("deposit_a");

    let deposit_a = ft_deposit(
        &usdc,
        pool.id(),
        alice.id(),
        params_a["commitment"].as_str().unwrap(),
        params_a["amount"].as_str().unwrap().parse::<u128>().unwrap(),
        params_a["auditor_pubkey"].as_str().unwrap(),
        params_a["view_ct"].as_str().unwrap(),
        params_a["note_ct"].as_str().unwrap(),
        &proof_a,
    )
    .await?;
    assert!(deposit_a.is_success(), "deposit A failed: {deposit_a:#?}");

    let root_after_a: String = pool.view("merkle_root").await?.json()?;
    eprintln!("root_after_A: {root_after_a}");
    assert_ne!(root_after_a, pre_root, "deposit A must change merkle root");
    assert_eq!(
        root_after_a,
        params_a["root_after"].as_str().unwrap(),
        "root after deposit A must match fixture (off-chain tree parity)"
    );

    // ----- DEPOSIT B (amount=40, index=1) -----------------------------------
    let params_b = read_params("deposit_b");
    let proof_b = read_proof("deposit_b");

    let deposit_b = ft_deposit(
        &usdc,
        pool.id(),
        alice.id(),
        params_b["commitment"].as_str().unwrap(),
        params_b["amount"].as_str().unwrap().parse::<u128>().unwrap(),
        params_b["auditor_pubkey"].as_str().unwrap(),
        params_b["view_ct"].as_str().unwrap(),
        params_b["note_ct"].as_str().unwrap(),
        &proof_b,
    )
    .await?;
    assert!(deposit_b.is_success(), "deposit B failed: {deposit_b:#?}");

    let root_after_b: String = pool.view("merkle_root").await?.json()?;
    eprintln!("root_after_B (= transfer root R2): {root_after_b}");
    assert_eq!(
        root_after_b,
        params_b["root_after"].as_str().unwrap(),
        "root after deposit B must match fixture"
    );

    // ----- TRANSFER (spend A@0+B@1 at R2, produce out0@2+out1@3) -----------
    let params_t = read_params("transfer");
    let proof_t = read_proof("transfer");

    let nullifiers_t = params_t["nullifiers"].as_array().unwrap();
    let commitments_t = params_t["commitments"].as_array().unwrap();
    let view_cts_t = params_t["view_cts"].as_array().unwrap();
    let note_cts_t = params_t["note_cts"].as_array().unwrap();

    // Nullifiers must not be spent yet.
    for nul in nullifiers_t {
        let n_hex = nul.as_str().unwrap();
        let spent: bool = pool
            .view("is_nullifier_spent")
            .args_json(json!({ "n_hex": n_hex }))
            .await?
            .json()?;
        assert!(!spent, "nullifier {n_hex} must be unspent before transfer");
    }

    let transfer = alice
        .call(pool.id(), "transfer")
        .args_json(json!({
            "merkle_root": params_t["merkle_root"].as_str().unwrap(),
            "nullifiers": [
                nullifiers_t[0].as_str().unwrap(),
                nullifiers_t[1].as_str().unwrap(),
            ],
            "commitments": [
                commitments_t[0].as_str().unwrap(),
                commitments_t[1].as_str().unwrap(),
            ],
            "auditor_pubkey": params_t["auditor_pubkey"].as_str().unwrap(),
            "recipient_auditor_pubkey": params_t["recipient_auditor_pubkey"].as_str().unwrap(),
            "view_cts": [
                view_cts_t[0].as_str().unwrap(),
                view_cts_t[1].as_str().unwrap(),
            ],
            "note_cts": [
                note_cts_t[0].as_str().unwrap(),
                note_cts_t[1].as_str().unwrap(),
            ],
            "proof": proof_t,
        }))
        .deposit(near_workspaces::types::NearToken::from_yoctonear(one_near))
        .max_gas()
        .transact()
        .await?;
    assert!(transfer.is_success(), "transfer failed: {transfer:#?}");

    // Both nullifiers spent.
    for nul in nullifiers_t {
        let n_hex = nul.as_str().unwrap();
        let spent: bool = pool
            .view("is_nullifier_spent")
            .args_json(json!({ "n_hex": n_hex }))
            .await?
            .json()?;
        assert!(spent, "nullifier {n_hex} must be spent after transfer");
    }

    let root_after_t: String = pool.view("merkle_root").await?.json()?;
    eprintln!("root_after_transfer (R3): {root_after_t}");
    assert_eq!(
        root_after_t,
        params_t["root_after"].as_str().unwrap(),
        "root after transfer must match fixture"
    );

    // ----- WITHDRAW (spend out1@3 at R3) ------------------------------------
    let params_w = read_params("withdraw");
    let proof_w = read_proof("withdraw");

    let nullifier_w = params_w["nullifier"].as_str().unwrap();
    let spent_before: bool = pool
        .view("is_nullifier_spent")
        .args_json(json!({ "n_hex": nullifier_w }))
        .await?
        .json()?;
    assert!(!spent_before, "withdraw nullifier must be unspent before withdraw");

    let relayer = worker.dev_create_account().await?;
    let withdraw = relayer
        .call(pool.id(), "withdraw")
        .args_json(json!({
            "merkle_root": params_w["merkle_root"].as_str().unwrap(),
            "nullifier": nullifier_w,
            "recipient": params_w["recipient"].as_str().unwrap(),
            "amount": U128(params_w["amount"].as_str().unwrap().parse::<u128>().unwrap()),
            "auditor_pubkey": params_w["auditor_pubkey"].as_str().unwrap(),
            "view_ct": params_w["view_ct"].as_str().unwrap(),
            "relayer": params_w["relayer"].as_str().unwrap(),
            "relayer_fee": U128(params_w["relayer_fee"].as_str().unwrap().parse::<u128>().unwrap()),
            "proof": proof_w,
        }))
        .deposit(near_workspaces::types::NearToken::from_yoctonear(one_near))
        .max_gas()
        .transact()
        .await?;

    // The chained ft_transfer to the fake USDC account will fail (no real NEP-141
    // contract deployed), but the state mutations (nullifier spent, event) happen
    // before that resolves — exactly as in the existing test.
    let logs = withdraw.logs();
    let saw_withdraw = logs.iter().any(|l| l.contains("\"event\":\"withdraw\""));
    assert!(
        saw_withdraw,
        "no withdraw event (proof likely rejected): {logs:#?}\n{withdraw:#?}"
    );

    let spent_after: bool = pool
        .view("is_nullifier_spent")
        .args_json(json!({ "n_hex": nullifier_w }))
        .await?
        .json()?;
    assert!(spent_after, "withdraw nullifier must be spent after withdraw");

    // Double-spend must be rejected.
    let double = relayer
        .call(pool.id(), "withdraw")
        .args_json(json!({
            "merkle_root": params_w["merkle_root"].as_str().unwrap(),
            "nullifier": nullifier_w,
            "recipient": params_w["recipient"].as_str().unwrap(),
            "amount": U128(params_w["amount"].as_str().unwrap().parse::<u128>().unwrap()),
            "auditor_pubkey": params_w["auditor_pubkey"].as_str().unwrap(),
            "view_ct": params_w["view_ct"].as_str().unwrap(),
            "relayer": params_w["relayer"].as_str().unwrap(),
            "relayer_fee": U128(params_w["relayer_fee"].as_str().unwrap().parse::<u128>().unwrap()),
            "proof": proof_w,
        }))
        .deposit(near_workspaces::types::NearToken::from_yoctonear(one_near))
        .max_gas()
        .transact()
        .await?;
    assert!(double.is_failure(), "double-spend must be rejected: {double:#?}");

    eprintln!("ALL ASSERTIONS PASSED: connected snarkjs-fixture e2e flow complete.");
    Ok(())
}

/// Security regression: the direct `deposit()` entry point inserts a commitment
/// into the tree with NO backing USDC transfer.
#[tokio::test]
async fn production_build_does_not_expose_direct_deposit() -> anyhow::Result<()> {
    // Drift guard: catch fixture/circuit mismatch even if only this test runs.
    assert_fixture_not_drifted();

    if skip() {
        eprintln!("SKIP_NEAR_INTEGRATION set; skipping sandbox");
        return Ok(());
    }
    let pool_wasm = load_deployable_wasm()?;
    let worker = near_workspaces::sandbox().await?;
    let pool = worker.dev_deploy(&pool_wasm).await?;
    let usdc = worker.dev_create_account().await?;

    let vk_deposit = std::fs::read(format!("{VK_DIR}/deposit/vk.bin"))?;
    let vk_transfer = std::fs::read(format!("{VK_DIR}/transfer/vk.bin"))?;
    let vk_withdraw = std::fs::read(format!("{VK_DIR}/withdraw/vk.bin"))?;

    pool.call("new")
        .args_json(json!({
            "owner": pool.id(),
            "usdc_token": usdc.id(),
            "vk_deposit": vk_deposit,
            "vk_transfer": vk_transfer,
            "vk_withdraw": vk_withdraw,
        }))
        .max_gas()
        .transact()
        .await?
        .into_result()?;

    let one_near = near_sdk::NearToken::from_near(1).as_yoctonear();
    let attempt = usdc
        .call(pool.id(), "deposit")
        .args_json(json!({
            "commitment": format!("0x{}", "01".repeat(32)),
            "amount": U128(1_000_000),
            "auditor_pubkey": format!("0x{}", "02".repeat(32)),
            "view_ct": "v",
            "note_ct": "n",
            "proof": vec![1u8, 2, 3],
        }))
        .deposit(near_workspaces::types::NearToken::from_yoctonear(one_near))
        .max_gas()
        .transact()
        .await?;

    let detail = format!("{attempt:#?}");
    assert!(
        attempt.is_failure(),
        "direct deposit must not succeed in a deployable build: {detail}"
    );
    assert!(
        detail.contains("MethodResolveError") || detail.contains("MethodNotFound"),
        "direct deposit() must be absent (expected MethodNotFound) in a deployable build: {detail}"
    );
    Ok(())
}
