//! End-to-end real-proof integration test.
//!
//! Deploys the REAL `groth16-verifier` build of the shielded-pool contract to a
//! near-workspaces sandbox, initialises it with verifying keys generated by the
//! `shielded-prover` CLI, and drives a real-proof DEPOSIT -> WITHDRAW (and, as a
//! bonus, TRANSFER) flow. Unlike `integration.rs` (which uses the permissive
//! MockVerifier build), every proof here is produced by the arkworks Groth16
//! prover and checked on-chain by NEAR's `alt_bn128_*` host functions.
//!
//! Gated by the SAME env var as `integration.rs`: set `SKIP_NEAR_INTEGRATION`
//! to skip the sandbox portion. Proof generation and all off-chain hashing run
//! regardless of the gate so the prover wiring is always exercised.
//!
//! Build prerequisites (the test will error with guidance if missing):
//!   cargo build -p shielded-pool --target wasm32-unknown-unknown --release \
//!     --no-default-features --features groth16-verifier
//!   cargo build -p shielded-prover --release
//!   cargo run -p shielded-prover --release -- setup --out-dir target/sp-keys
//!
//! Off-chain hashing reuses the contract's own Poseidon (`shielded_pool::poseidon`),
//! which is the canonical Circom-parameter Poseidon shared by contract, circuits,
//! and SDK (cross-checked by `poseidon2_known_vector` / `poseidon4_known_vector`).
//! This avoids a dev-dependency cycle with `shielded-prover` (which already
//! dev-depends on `shielded-pool`).

use near_sdk::json_types::U128;
use serde_json::json;
use shielded_pool::deposit::hash_bytes_to_field as contract_hash_bytes;
use shielded_pool::poseidon::{poseidon2, poseidon4, Field};
use std::io::Write;
use std::process::{Command, Stdio};

/// REAL groth16-verifier WASM (NOT the `.integration.opt.wasm` mock build).
/// NEAR's runtime rejects the raw cargo-emitted module (it carries features the
/// sandbox can't deserialise), so we deploy the `wasm-opt`-processed artifact —
/// the same one `scripts/check-production-readiness.sh` produces for deployment.
const OPT_WASM_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../target/wasm32-unknown-unknown/release/shielded_pool.opt.wasm"
);
const RAW_WASM_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../target/wasm32-unknown-unknown/release/shielded_pool.wasm"
);

const PROVER_BIN: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/../target/release/shielded-prover");

const KEY_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../target/sp-keys");

const TREE_DEPTH: usize = 20;

// ---------------------------------------------------------------------------
// Off-chain hash helpers (mirror the circuit witness derivation).
// ---------------------------------------------------------------------------

fn fr_hex(f: Field) -> String {
    f.to_hex()
}

/// commit_note = poseidon4(amount, owner, auditor, blinding).
fn commit_note(amount: Field, owner: Field, auditor: Field, blinding: Field) -> Field {
    poseidon4(amount, owner, auditor, blinding)
}

/// owner_pubkey_of(sk) = poseidon2(sk, 0).
fn owner_pubkey_of(sk: Field) -> Field {
    poseidon2(sk, Field::zero())
}

/// nullifier_of(sk, c, i) = poseidon2(sk, poseidon2(c, i)).
fn nullifier_of(sk: Field, c: Field, i: Field) -> Field {
    poseidon2(sk, poseidon2(c, i))
}

/// Zero-subtree sibling at each level: zeros[0]=0, zeros[k]=poseidon2(z,z).
fn zero_levels() -> [Field; TREE_DEPTH] {
    let mut z = Field::zero();
    let mut zeros = [Field::zero(); TREE_DEPTH];
    for level in zeros.iter_mut() {
        *level = z;
        z = poseidon2(z, z);
    }
    zeros
}

/// Root + merkle path for a single leaf inserted at index 0 of an otherwise
/// empty depth-20 tree. Matches the contract's `IncrementalMerkleTree` first
/// insert (which folds the leaf up against zero siblings) and the prover's
/// `empty_path_for_leaf0`.
fn empty_path_for_leaf0(leaf: Field) -> (Field, [Field; TREE_DEPTH]) {
    let zeros = zero_levels();
    let mut current = leaf;
    for level in zeros.iter() {
        current = poseidon2(current, *level);
    }
    (current, zeros)
}

/// Root + paths for two leaves at indices 0 and 1 of an empty depth-20 tree.
/// path0[0] = leaf1 (right sibling), path1[0] = leaf0 (left sibling), all
/// higher levels are zero siblings. Mirrors the prover's `tree_two`.
fn tree_with_two_leaves(
    leaf0: Field,
    leaf1: Field,
) -> (Field, [Field; TREE_DEPTH], [Field; TREE_DEPTH]) {
    let zeros = zero_levels();
    let mut path0 = zeros;
    let mut path1 = zeros;
    path0[0] = leaf1;
    path1[0] = leaf0;
    let mut current = poseidon2(leaf0, leaf1);
    for level in zeros.iter().skip(1) {
        current = poseidon2(current, *level);
    }
    (current, path0, path1)
}

// ---------------------------------------------------------------------------
// Proof generation: shell out to the prover binary.
// ---------------------------------------------------------------------------

/// Spawns `shielded-prover` with PROVER_KEY_DIR=key_dir, pipes a ProveRequest
/// JSON to stdin, and returns the raw proof bytes from stdout (asserted to be
/// exactly 256 bytes).
fn prove(circuit: &str, public_inputs: &[String], witness: serde_json::Value) -> Vec<u8> {
    let req = json!({
        "circuit": circuit,
        "publicInputs": public_inputs,
        "witness": witness,
    });
    let mut child = Command::new(PROVER_BIN)
        .env("PROVER_KEY_DIR", KEY_DIR)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap_or_else(|e| {
            panic!(
                "failed to spawn prover at {PROVER_BIN}: {e}. \
                 Build it with `cargo build -p shielded-prover --release`."
            )
        });
    child
        .stdin
        .take()
        .unwrap()
        .write_all(serde_json::to_string(&req).unwrap().as_bytes())
        .unwrap();
    let out = child.wait_with_output().unwrap();
    assert!(
        out.status.success(),
        "prover failed for circuit '{circuit}': {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert_eq!(
        out.stdout.len(),
        256,
        "proof for '{circuit}' must be 256 bytes, got {}",
        out.stdout.len()
    );
    out.stdout
}

fn skip() -> bool {
    std::env::var("SKIP_NEAR_INTEGRATION").is_ok()
}

/// Loads the deployable (wasm-opt'd) groth16-verifier WASM. If the optimised
/// artifact is missing but the raw cargo output exists, runs `wasm-opt` to
/// produce it (same flags as `scripts/check-production-readiness.sh`).
///
/// `--llvm-memory-copy-fill-lowering` is required: since Rust 1.87 the
/// wasm32-unknown-unknown target emits `memory.copy`/`memory.fill` (bulk-memory)
/// from precompiled std, which the NEAR runtime rejects at deploy time with
/// `PrepareError(Deserialization)`. The pass lowers them back to MVP.
fn load_deployable_wasm() -> anyhow::Result<Vec<u8>> {
    if !std::path::Path::new(OPT_WASM_PATH).exists() {
        anyhow::ensure!(
            std::path::Path::new(RAW_WASM_PATH).exists(),
            "missing groth16-verifier wasm at {RAW_WASM_PATH}. Build with: \
             cargo build -p shielded-pool --target wasm32-unknown-unknown --release \
             --no-default-features --features groth16-verifier"
        );
        let status = Command::new("wasm-opt")
            .args([
                "--enable-bulk-memory",
                "--llvm-memory-copy-fill-lowering",
                "-Oz",
                "--strip-debug",
                "--strip-producers",
                RAW_WASM_PATH,
                "-o",
                OPT_WASM_PATH,
            ])
            .status()
            .map_err(|e| {
                anyhow::anyhow!(
                    "wasm-opt not found ({e}); produce the deployable artifact with: \
                     wasm-opt --enable-bulk-memory --llvm-memory-copy-fill-lowering -Oz \
                     --strip-debug --strip-producers {RAW_WASM_PATH} -o {OPT_WASM_PATH}"
                )
            })?;
        anyhow::ensure!(status.success(), "wasm-opt failed");
    }
    Ok(std::fs::read(OPT_WASM_PATH)?)
}

/// Deposit via the production NEP-141 path: the configured `usdc` account calls
/// `ft_on_transfer` with the DepositArgs payload as `msg`. This is the only
/// deposit entry point in a deployable build (the direct `deposit()` is gated
/// out — see `production_build_does_not_expose_direct_deposit`).
#[allow(clippy::too_many_arguments)]
async fn ft_deposit(
    usdc: &near_workspaces::Account,
    pool_id: &near_workspaces::AccountId,
    sender_id: &near_workspaces::AccountId,
    commitment: Field,
    amount: u128,
    auditor: Field,
    view_ct: &str,
    note_ct: &str,
    proof: &[u8],
) -> anyhow::Result<near_workspaces::result::ExecutionFinalResult> {
    let msg = serde_json::to_string(&json!({
        "commitment": fr_hex(commitment),
        "amount": U128(amount),
        "auditor_pubkey": fr_hex(auditor),
        "view_ct": view_ct,
        "note_ct": note_ct,
        "proof": proof,
    }))?;
    Ok(usdc
        .call(pool_id, "ft_on_transfer")
        .args_json(json!({
            "sender_id": sender_id,
            "amount": U128(amount),
            "msg": msg,
        }))
        .max_gas()
        .transact()
        .await?)
}

#[tokio::test]
async fn real_proof_deposit_withdraw_transfer() -> anyhow::Result<()> {
    // ----- Off-chain note + proof construction (always runs) -------------
    // Deposited note: the seed values from the prover's own circuit tests.
    let sk = Field::from_u64(7);
    let owner = owner_pubkey_of(sk);
    let auditor = Field::from_u64(22);
    let blinding = Field::from_u64(33);
    let amount: u128 = 1_000_000;
    let amount_f = Field::from_u128(amount);
    let commitment = commit_note(amount_f, owner, auditor, blinding);

    let view_ct = "view_ct_payload";
    let note_ct = "note_ct_payload";
    let view_ct_hash = contract_hash_bytes(view_ct.as_bytes());

    // DEPOSIT proof: PI = [commitment, amount, auditor, view_ct_hash].
    let deposit_pi = vec![
        fr_hex(commitment),
        fr_hex(amount_f),
        fr_hex(auditor),
        fr_hex(view_ct_hash),
    ];
    let deposit_witness = json!({
        "ownerPubkey": fr_hex(owner),
        "blinding": fr_hex(blinding),
        "viewCtHashWitness": fr_hex(view_ct_hash),
    });
    let deposit_proof = prove("deposit", &deposit_pi, deposit_witness);
    eprintln!("deposit proof generated: {} bytes", deposit_proof.len());

    // WITHDRAW proof for the note at leaf index 0.
    // Contract derives recipient/relayer public inputs by hashing the account
    // id bytes; the withdraw circuit passes these straight through, so the
    // witness recipient/relayer just need to equal the contract's computed PI.
    let w_recipient_id = "bob.test.near";
    let w_relayer_id = "relayer.test.near";
    let w_recipient = contract_hash_bytes(w_recipient_id.as_bytes());
    let w_relayer = contract_hash_bytes(w_relayer_id.as_bytes());
    let w_relayer_fee: u128 = 5_000;
    let w_view_ct = "view_ct_withdraw";
    let w_view_ct_hash = contract_hash_bytes(w_view_ct.as_bytes());
    let nullifier = nullifier_of(sk, commitment, Field::zero());
    let (deposit_root, w_path) = empty_path_for_leaf0(commitment);

    let withdraw_pi = vec![
        fr_hex(deposit_root),
        fr_hex(nullifier),
        fr_hex(w_recipient),
        fr_hex(amount_f),
        fr_hex(w_relayer),
        fr_hex(Field::from_u128(w_relayer_fee)),
        fr_hex(auditor),
        fr_hex(w_view_ct_hash),
    ];
    let withdraw_witness = json!({
        "noteAmount": fr_hex(amount_f),
        "noteOwnerPubkey": fr_hex(owner),
        "noteAuditorPubkey": fr_hex(auditor),
        "noteBlinding": fr_hex(blinding),
        "spendingKey": fr_hex(sk),
        "leafIndex": fr_hex(Field::zero()),
        "merklePath": w_path.iter().map(|f| fr_hex(*f)).collect::<Vec<_>>(),
        "viewCtHashWitness": fr_hex(w_view_ct_hash),
    });
    let withdraw_proof = prove("withdraw", &withdraw_pi, withdraw_witness);
    eprintln!("withdraw proof generated: {} bytes", withdraw_proof.len());

    if skip() {
        eprintln!("SKIP_NEAR_INTEGRATION set; proofs generated, skipping sandbox");
        return Ok(());
    }

    // ----- Sandbox: deploy real verifier, init with real VKs --------------
    let pool_wasm = load_deployable_wasm()?;

    let vk_deposit = std::fs::read(format!("{KEY_DIR}/deposit.vk"))?;
    let vk_transfer = std::fs::read(format!("{KEY_DIR}/transfer.vk"))?;
    let vk_withdraw = std::fs::read(format!("{KEY_DIR}/withdraw.vk"))?;

    let worker = near_workspaces::sandbox().await?;
    let pool = worker.dev_deploy(&pool_wasm).await?;
    // Stand-in USDC account: deposits arrive via `ft_on_transfer`, whose only
    // caller-guard is `predecessor == usdc_token`. We don't deploy a full
    // NEP-141 here — the pool's payout `ft_transfer` to this account fails
    // harmlessly (tolerated below), which is enough to exercise the state path.
    let usdc = worker.dev_create_account().await?;

    let init = pool
        .call("new")
        .args_json(json!({
            "owner": pool.id(),
            "usdc_token": usdc.id(),
            "vk_deposit": vk_deposit,
            "vk_transfer": vk_transfer,
            "vk_withdraw": vk_withdraw,
        }))
        .max_gas()
        .transact()
        .await?;
    assert!(init.is_success(), "init failed: {init:#?}");

    let pre_root: String = pool.view("merkle_root").await?.json()?;

    // Storage deposit: cover the per-action byte cost with margin.
    let one_near = near_sdk::NearToken::from_near(1).as_yoctonear();

    // ----- DEPOSIT (real proof, via ft_on_transfer) -----------------------
    let alice = worker.dev_create_account().await?;
    let deposit = ft_deposit(
        &usdc,
        pool.id(),
        alice.id(),
        commitment,
        amount,
        auditor,
        view_ct,
        note_ct,
        &deposit_proof,
    )
    .await?;
    assert!(deposit.is_success(), "real-proof deposit failed: {deposit:#?}");

    let root_after_deposit: String = pool.view("merkle_root").await?.json()?;
    assert_ne!(root_after_deposit, pre_root, "deposit must change merkle root");
    // The off-chain root we computed for the single leaf must match on-chain.
    assert_eq!(
        root_after_deposit,
        fr_hex(deposit_root),
        "off-chain leaf0 root must match contract tree root"
    );

    // Nullifier not yet spent.
    let spent_before: bool = pool
        .view("is_nullifier_spent")
        .args_json(json!({ "n_hex": fr_hex(nullifier) }))
        .await?
        .json()?;
    assert!(!spent_before, "nullifier should be unspent before withdraw");

    // ----- WITHDRAW (real proof) ------------------------------------------
    let relayer = worker.dev_create_account().await?;
    let withdraw = relayer
        .call(pool.id(), "withdraw")
        .args_json(json!({
            "merkle_root": root_after_deposit,
            "nullifier": fr_hex(nullifier),
            "recipient": w_recipient_id,
            "amount": U128(amount),
            "auditor_pubkey": fr_hex(auditor),
            "view_ct": w_view_ct,
            "relayer": w_relayer_id,
            "relayer_fee": U128(w_relayer_fee),
            "proof": withdraw_proof,
        }))
        .deposit(near_workspaces::types::NearToken::from_yoctonear(one_near))
        .max_gas()
        .transact()
        .await?;
    // The chained ft_transfer to the fake USDC account fails, but the state
    // mutations (nullifier spent, event) happen before that resolves.
    let logs = withdraw.logs();
    let saw_withdraw = logs
        .iter()
        .any(|l| l.contains("\"event\":\"withdraw\""));
    assert!(
        saw_withdraw,
        "no withdraw event (proof likely rejected): {logs:#?} :: {withdraw:#?}"
    );

    let spent_after: bool = pool
        .view("is_nullifier_spent")
        .args_json(json!({ "n_hex": fr_hex(nullifier) }))
        .await?
        .json()?;
    assert!(spent_after, "nullifier must be spent after withdraw");

    // Double-spend rejection on chain (re-using the same proof).
    let double = relayer
        .call(pool.id(), "withdraw")
        .args_json(json!({
            "merkle_root": root_after_deposit,
            "nullifier": fr_hex(nullifier),
            "recipient": w_recipient_id,
            "amount": U128(amount),
            "auditor_pubkey": fr_hex(auditor),
            "view_ct": w_view_ct,
            "relayer": w_relayer_id,
            "relayer_fee": U128(w_relayer_fee),
            "proof": withdraw_proof,
        }))
        .deposit(near_workspaces::types::NearToken::from_yoctonear(one_near))
        .max_gas()
        .transact()
        .await?;
    assert!(double.is_failure(), "double spend must reject: {double:#?}");

    // ----- TRANSFER (bonus): real proof spending two fresh deposits -------
    // Deposit two notes (indices 1 and 2 now exist; we build a fresh tree view
    // for the transfer by depositing into the SAME contract). For a clean,
    // self-contained transfer proof we use two notes at indices 0,1 of an empty
    // tree — so we run the transfer flow against a SECOND freshly deployed pool.
    let pool2 = worker.dev_deploy(&pool_wasm).await?;
    pool2
        .call("new")
        .args_json(json!({
            "owner": pool2.id(),
            "usdc_token": usdc.id(),
            "vk_deposit": std::fs::read(format!("{KEY_DIR}/deposit.vk"))?,
            "vk_transfer": std::fs::read(format!("{KEY_DIR}/transfer.vk"))?,
            "vk_withdraw": std::fs::read(format!("{KEY_DIR}/withdraw.vk"))?,
        }))
        .max_gas()
        .transact()
        .await?
        .into_result()?;

    // Two input notes owned by sk, auditor=22.
    let t_auditor = Field::from_u64(22);
    let t_recip_auditor = Field::from_u64(33);
    let c_in0 = commit_note(Field::from_u64(60), owner, t_auditor, Field::from_u64(1));
    let c_in1 = commit_note(Field::from_u64(40), owner, t_auditor, Field::from_u64(2));

    // Deposit c_in0 then c_in1 -> indices 0 and 1.
    for (c, amt, vct, nct) in [
        (c_in0, 60u128, "vct_in0", "nct_in0"),
        (c_in1, 40u128, "vct_in1", "nct_in1"),
    ] {
        let amt_f = Field::from_u128(amt);
        let vh = contract_hash_bytes(vct.as_bytes());
        let pi = vec![fr_hex(c), fr_hex(amt_f), fr_hex(t_auditor), fr_hex(vh)];
        // owner/blinding witness: blinding 1 for c_in0, 2 for c_in1.
        let blind = if amt == 60 { 1u64 } else { 2u64 };
        let wit = json!({
            "ownerPubkey": fr_hex(owner),
            "blinding": fr_hex(Field::from_u64(blind)),
            "viewCtHashWitness": fr_hex(vh),
        });
        let proof = prove("deposit", &pi, wit);
        ft_deposit(
            &usdc,
            pool2.id(),
            alice.id(),
            c,
            amt,
            t_auditor,
            vct,
            nct,
            &proof,
        )
        .await?
        .into_result()?;
    }

    let transfer_root: String = pool2.view("merkle_root").await?.json()?;
    let (root_off, path0, path1) = tree_with_two_leaves(c_in0, c_in1);
    assert_eq!(transfer_root, fr_hex(root_off), "two-leaf root mismatch");

    // Output notes: 70 + 30 = 100 = 60 + 40. out0 owner=100 (arbitrary), out1 owner=owner.
    let cout0 = commit_note(
        Field::from_u64(70),
        Field::from_u64(100),
        t_recip_auditor,
        Field::from_u64(3),
    );
    let cout1 = commit_note(Field::from_u64(30), owner, t_recip_auditor, Field::from_u64(4));
    let n0 = nullifier_of(sk, c_in0, Field::zero());
    let n1 = nullifier_of(sk, c_in1, Field::from_u64(1));
    let t_vct_sender = "vct_sender";
    let t_vct_recip = "vct_recip";
    let vh_sender = contract_hash_bytes(t_vct_sender.as_bytes());
    let vh_recip = contract_hash_bytes(t_vct_recip.as_bytes());

    let transfer_pi = vec![
        fr_hex(root_off),
        fr_hex(n0),
        fr_hex(n1),
        fr_hex(cout0),
        fr_hex(cout1),
        fr_hex(t_auditor),
        fr_hex(t_recip_auditor),
        fr_hex(vh_sender),
        fr_hex(vh_recip),
    ];
    let transfer_witness = json!({
        "in0Amount": fr_hex(Field::from_u64(60)),
        "in0OwnerPubkey": fr_hex(owner),
        "in0Blinding": fr_hex(Field::from_u64(1)),
        "in0LeafIndex": fr_hex(Field::zero()),
        "in0Path": path0.iter().map(|f| fr_hex(*f)).collect::<Vec<_>>(),
        "in1Amount": fr_hex(Field::from_u64(40)),
        "in1OwnerPubkey": fr_hex(owner),
        "in1Blinding": fr_hex(Field::from_u64(2)),
        "in1LeafIndex": fr_hex(Field::from_u64(1)),
        "in1Path": path1.iter().map(|f| fr_hex(*f)).collect::<Vec<_>>(),
        "spendingKey": fr_hex(sk),
        "out0Amount": fr_hex(Field::from_u64(70)),
        "out0OwnerPubkey": fr_hex(Field::from_u64(100)),
        "out0Blinding": fr_hex(Field::from_u64(3)),
        "out1Amount": fr_hex(Field::from_u64(30)),
        "out1OwnerPubkey": fr_hex(owner),
        "out1Blinding": fr_hex(Field::from_u64(4)),
        "viewCtHashSenderWitness": fr_hex(vh_sender),
        "viewCtHashRecipientWitness": fr_hex(vh_recip),
    });
    let transfer_proof = prove("transfer", &transfer_pi, transfer_witness);
    eprintln!("transfer proof generated: {} bytes", transfer_proof.len());

    let transfer = alice
        .call(pool2.id(), "transfer")
        .args_json(json!({
            "merkle_root": transfer_root,
            "nullifiers": [fr_hex(n0), fr_hex(n1)],
            "commitments": [fr_hex(cout0), fr_hex(cout1)],
            "auditor_pubkey": fr_hex(t_auditor),
            "recipient_auditor_pubkey": fr_hex(t_recip_auditor),
            "view_cts": [t_vct_sender, t_vct_recip],
            "note_cts": ["nct_s", "nct_r"],
            "proof": transfer_proof,
        }))
        .deposit(near_workspaces::types::NearToken::from_yoctonear(one_near))
        .max_gas()
        .transact()
        .await?;
    assert!(transfer.is_success(), "real-proof transfer failed: {transfer:#?}");

    let n0_spent: bool = pool2
        .view("is_nullifier_spent")
        .args_json(json!({ "n_hex": fr_hex(n0) }))
        .await?
        .json()?;
    let n1_spent: bool = pool2
        .view("is_nullifier_spent")
        .args_json(json!({ "n_hex": fr_hex(n1) }))
        .await?
        .json()?;
    assert!(n0_spent && n1_spent, "transfer nullifiers must be spent");

    Ok(())
}

/// Security regression: the direct `deposit()` entry point inserts a commitment
/// into the tree with NO backing USDC transfer — the deposit proof only attests
/// commitment well-formedness (no secret, no funds), and proving keys are
/// public, so anyone could mint unbacked notes and drain the pool. Deposits MUST
/// go through `ft_on_transfer`, which binds the amount to a real token transfer.
/// A deployable (groth16-verifier) build must therefore NOT expose `deposit()`.
#[tokio::test]
async fn production_build_does_not_expose_direct_deposit() -> anyhow::Result<()> {
    if skip() {
        eprintln!("SKIP_NEAR_INTEGRATION set; skipping sandbox");
        return Ok(());
    }
    let pool_wasm = load_deployable_wasm()?;
    let worker = near_workspaces::sandbox().await?;
    let pool = worker.dev_deploy(&pool_wasm).await?;
    let usdc = worker.dev_create_account().await?;
    pool.call("new")
        .args_json(json!({
            "owner": pool.id(),
            "usdc_token": usdc.id(),
            "vk_deposit": std::fs::read(format!("{KEY_DIR}/deposit.vk"))?,
            "vk_transfer": std::fs::read(format!("{KEY_DIR}/transfer.vk"))?,
            "vk_withdraw": std::fs::read(format!("{KEY_DIR}/withdraw.vk"))?,
        }))
        .max_gas()
        .transact()
        .await?
        .into_result()?;

    let one_near = near_sdk::NearToken::from_near(1).as_yoctonear();
    let attempt = usdc
        .call(pool.id(), "deposit")
        .args_json(json!({
            "commitment": fr_hex(Field::from_u64(1)),
            "amount": U128(1_000_000),
            "auditor_pubkey": fr_hex(Field::from_u64(2)),
            "view_ct": "v",
            "note_ct": "n",
            "proof": vec![1u8, 2, 3],
        }))
        .deposit(near_workspaces::types::NearToken::from_yoctonear(one_near))
        .max_gas()
        .transact()
        .await?;

    let detail = format!("{attempt:#?}");
    assert!(
        attempt.is_failure(),
        "direct deposit must not succeed in a deployable build: {detail}"
    );
    assert!(
        detail.contains("MethodResolveError") || detail.contains("MethodNotFound"),
        "direct deposit() must be absent (expected MethodNotFound) in a deployable build: {detail}"
    );
    Ok(())
}
