//! Kill-gate: real snarkjs Groth16 proofs for all three circuits must verify
//! via the contract's `verify_groth16` (NEAR alt_bn128 host functions).
//!
//! Fixtures are generated by `circom/scripts/gen-fixtures.ts` and committed to
//! `circom/fixtures/<circuit>/`.  Run with:
//!
//!   cargo test -p shielded-pool --test snarkjs_verify_fixture
//!
//! (The default `unit-testing` feature enables the NEAR mocked environment.)

use near_sdk::test_utils::VMContextBuilder;
use near_sdk::testing_env;
use shielded_pool::groth16::{verify_groth16, Proof, VerifyingKey};
use shielded_pool::poseidon::Field;

fn fixture_base_dir() -> String {
    // If CEREMONY_FIXTURE_DIR is set at runtime, load ceremony fixtures from there.
    // Otherwise fall back to the committed dev fixtures in circom/fixtures/.
    match std::env::var("CEREMONY_FIXTURE_DIR") {
        Ok(dir) if !dir.is_empty() => dir,
        _ => format!("{}/{}", env!("CARGO_MANIFEST_DIR"), "/../circom/fixtures"),
    }
}

fn load_fixture(circuit: &str, file: &str) -> Vec<u8> {
    let base = fixture_base_dir();
    let path = format!("{}/{}/{}", base, circuit, file);
    std::fs::read(&path).unwrap_or_else(|e| panic!("failed to read {}: {}", path, e))
}

fn parse_public_inputs(public_bin: &[u8]) -> Vec<Field> {
    assert_eq!(
        public_bin.len() % 32,
        0,
        "public.bin length must be a multiple of 32"
    );
    public_bin
        .chunks(32)
        .map(|chunk| Field::from_be_bytes(chunk))
        .collect()
}

#[test]
fn deposit_fixture_verifies() {
    testing_env!(VMContextBuilder::new().build());

    let vk_bin = load_fixture("deposit", "vk.bin");
    let proof_bin = load_fixture("deposit", "proof.bin");
    let public_bin = load_fixture("deposit", "public.bin");

    let vk = VerifyingKey::from_bytes(&vk_bin).expect("parse deposit VK");
    let proof = Proof::from_bytes(&proof_bin).expect("parse deposit proof");
    let inputs = parse_public_inputs(&public_bin);

    let ok = verify_groth16(&vk, &proof, &inputs);
    assert!(ok, "deposit: verify_groth16 returned false for real snarkjs proof");
}

#[test]
fn transfer_fixture_verifies() {
    testing_env!(VMContextBuilder::new().build());

    let vk_bin = load_fixture("transfer", "vk.bin");
    let proof_bin = load_fixture("transfer", "proof.bin");
    let public_bin = load_fixture("transfer", "public.bin");

    let vk = VerifyingKey::from_bytes(&vk_bin).expect("parse transfer VK");
    let proof = Proof::from_bytes(&proof_bin).expect("parse transfer proof");
    let inputs = parse_public_inputs(&public_bin);

    let ok = verify_groth16(&vk, &proof, &inputs);
    assert!(ok, "transfer: verify_groth16 returned false for real snarkjs proof");
}

#[test]
fn withdraw_fixture_verifies() {
    testing_env!(VMContextBuilder::new().build());

    let vk_bin = load_fixture("withdraw", "vk.bin");
    let proof_bin = load_fixture("withdraw", "proof.bin");
    let public_bin = load_fixture("withdraw", "public.bin");

    let vk = VerifyingKey::from_bytes(&vk_bin).expect("parse withdraw VK");
    let proof = Proof::from_bytes(&proof_bin).expect("parse withdraw proof");
    let inputs = parse_public_inputs(&public_bin);

    let ok = verify_groth16(&vk, &proof, &inputs);
    assert!(ok, "withdraw: verify_groth16 returned false for real snarkjs proof");
}
