[package]
name = "shielded-pool"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# Used during local development. For WASM contract build, omit this feature.
default = ["unit-testing"]
unit-testing = ["near-sdk/unit-testing"]

[dependencies]
near-sdk = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
light-poseidon = "0.2"
ark-bn254 = "0.4"
ark-ff = "0.4"
hex = "0.4"

[dev-dependencies]
near-workspaces = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
