import { describe, it, expect } from "vitest";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { assembleInitArgs } from "./assemble.js";
import { deployToSandbox } from "./sandbox.js";

const REPO = resolve(import.meta.dirname, "../.."); // deploy/src -> repo root
const WASM = resolve(
  REPO,
  "target/wasm32-unknown-unknown/release/shielded_pool.opt.wasm"
);
const VK_DIR = resolve(REPO, "ceremony/out");
// prereqs: optimised WASM must exist AND all three ceremony vk.json files must be present.
// Build: `cargo build --target wasm32-unknown-unknown --release && wasm-opt ...`
// Ceremony VKs are generated by the trusted-setup ceremony scripts under ceremony/.
const prereqs =
  existsSync(WASM) &&
  ["deposit", "transfer", "withdraw"].every((c) =>
    existsSync(resolve(VK_DIR, c, "vk.json"))
  );

describe("deployToSandbox", () => {
  it.skipIf(!prereqs)(
    "deploys + inits + post-verifies the pool with ceremony VKs",
    async () => {
      const { initArgs } = assembleInitArgs(
        VK_DIR,
        "owner.test.near",
        "usdc.test.near"
      );
      const r = await deployToSandbox(WASM, initArgs);
      expect(r.ok).toBe(true);
      expect(r.owner).toBe("owner.test.near");
      expect(r.usdcToken).toBe("usdc.test.near");
      expect(r.paused).toBe(false);
    },
    120_000
  );
});
